# Generated by Django 2.0.2 on 2018-04-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_long', models.CharField(help_text='TV channel long name', max_length=30)),
                ('channel_short', models.CharField(help_text='TV channel short name', max_length=20)),
            ],
            options={
                'ordering': ['channel_long'],
            },
        ),
        migrations.CreateModel(
            name='VideoURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_description', models.CharField(help_text='Description of the URL', max_length=255)),
                ('video_url', models.CharField(help_text="Static URL's used to download video", max_length=200)),
            ],
        ),
    ]
