# Generated by Django 2.0.2 on 2018-04-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getvideo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videourl',
            name='url_code',
            field=models.CharField(default='', help_text='URL identificator', max_length=20),
        ),
    ]
