# Generated by Django 2.0.2 on 2018-05-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getvideo', '0003_videohistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videohistory',
            name='video_datetime',
            field=models.DateTimeField(help_text='Download date and time'),
        ),
    ]
