# Generated by Django 2.0.2 on 2018-05-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getvideo', '0004_auto_20180522_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videohistory',
            name='video_path',
            field=models.FilePathField(help_text='Video path', match='*.ts', path='/home/shahin/PythonProjects/myvideo/media'),
        ),
    ]
