# Generated by Django 2.0.2 on 2018-05-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getvideo', '0006_auto_20180522_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videohistory',
            name='video_path',
            field=models.CharField(help_text='Video path', max_length=255),
        ),
    ]
