# Generated by Django 2.0.2 on 2018-05-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getvideo', '0008_auto_20180522_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='videohistory',
            name='video_owner',
            field=models.CharField(blank=True, help_text='TV channel short name', max_length=30),
        ),
    ]
